# Generated by Django 2.1.7 on 2019-06-12 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('authtoken', '0002_auto_20160226_1747'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionToken',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True,
                                         serialize=False, verbose_name='Key')),
                ('type', models.CharField(
                    choices=[('account_activation', 'Account activation'),
                             ('password_change', 'Password change')],
                    max_length=100, verbose_name='Type of action')),
                ('created', models.DateTimeField(
                    auto_now_add=True,
                    verbose_name='Creation date')),
                ('expires', models.DateTimeField(
                    blank=True,
                    verbose_name='Expiration date')),
                ('user',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.CASCADE,
                     related_name='activation_token',
                     to=settings.AUTH_USER_MODEL,
                     verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='TemporaryToken',
            fields=[
                ('token_ptr', models.OneToOneField(
                    auto_created=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    parent_link=True,
                    primary_key=True,
                    serialize=False,
                    to='authtoken.Token')),
                ('expires', models.DateTimeField(
                    blank=True,
                    verbose_name='Expiration date')),
            ],
            options={
                'verbose_name': 'Temporary token',
                'verbose_name_plural': 'Temporary tokens',
            },
            bases=('authtoken.token',),
        ),
    ]
