# Generated by Django 2.2.12 on 2020-07-27 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200609_0105'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TemporaryToken',
        ),
    ]
