# Generated by Django 2.2.12 on 2021-01-18 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_delete_temporarytoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='private_note',
            field=models.TextField(blank=True, null=True, verbose_name='private note'),
        ),
    ]
