# Generated by Django 2.2.12 on 2021-03-28 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_apitoken'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='apitoken',
            unique_together={('user', 'purpose')},
        ),
    ]
