# Generated by Django 2.2.12 on 2021-02-04 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_apitoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='APITokenProxy',
            fields=[
            ],
            options={
                'verbose_name': 'token',
                'abstract': False,
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('user.apitoken',),
        ),
    ]
