# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-15 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiVolontaria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporarytoken',
            name='expires',
            field=models.DateTimeField(blank=True, verbose_name='Expiration date'),
        ),
    ]
