# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-15 00:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('apiVolontaria', '0002_auto_20171114_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporarytoken',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 15, 0, 33, 8, 164367, tzinfo=utc)),
        ),
    ]
