# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-15 00:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('apiVolontaria', '0003_auto_20171115_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporarytoken',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 15, 0, 54, 52, 115605, tzinfo=utc)),
        ),
    ]
