# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-15 02:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('apiVolontaria', '0004_auto_20171115_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporarytoken',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 15, 2, 53, 0, 279794, tzinfo=utc)),
        ),
    ]
