# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-20 20:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiVolontaria', '0002_auto_20171115_1949'),
        ('apiVolontaria', '0005_auto_20171115_0243'),
    ]

    operations = [
    ]
