# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-10 15:36
from __future__ import unicode_literals

from django.db import migrations, models

# App in which we are applying the migration
TARGET_APP = 'auth'


class Migration(migrations.Migration):
    """
    This custom migration is used to "patch" the default Django User model
    """

    def __init__(self, name, app_label):
        # overriding application operated upon
        super(Migration, self).__init__(name, TARGET_APP)

    # specify what original migration file it replaces
    # or leave migration loader confused about unapplied migration
    replaces = ((TARGET_APP, __module__.rsplit('.', 1)[-1]),)

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('apiVolontaria', '0005_profile')
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True,
                                    max_length=254,
                                    unique=True,
                                    verbose_name='email address'),
        ),
    ]
