# Generated by Django 2.1.5 on 2019-05-03 13:45

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfoSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, db_index=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Contenu')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
