# Generated by Django 2.1.5 on 2019-05-09 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='infosection',
            options={'ordering': ['sort_order'], 'verbose_name': 'Section page informations', 'verbose_name_plural': 'Sections page informations'},
        ),
        migrations.AddField(
            model_name='infosection',
            name='is_accordion',
            field=models.BooleanField(default=True, verbose_name='Accordeon'),
        ),
    ]
