# Generated by Django 2.2.10 on 2020-03-18 21:16

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20190509_1544'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='infosection',
            options={'ordering': ['sort_order'], 'verbose_name': 'Information Page section', 'verbose_name_plural': 'Information Page sections'},
        ),
        migrations.AlterField(
            model_name='infosection',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='infosection',
            name='is_accordion',
            field=models.BooleanField(default=True, verbose_name='Accordion'),
        ),
        migrations.AlterField(
            model_name='infosection',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='infosection',
            name='title',
            field=models.CharField(max_length=255, verbose_name='title'),
        ),
    ]
