# Generated by Django 2.2.12 on 2020-09-05 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('hourly_wage', models.FloatField(verbose_name='Hourly wage')),
                ('weekly_hours', models.FloatField(verbose_name='Hourly wage')),
                ('minimum_duration_commitment', models.FloatField(verbose_name='Minimum duration commitment')),
                ('is_remote_job', models.BooleanField(verbose_name='Job is remote ')),
                ('is_posted', models.BooleanField(verbose_name='Is posted')),
            ],
            options={
                'verbose_name': 'Position',
                'verbose_name_plural': 'Positions',
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_on', models.DateTimeField(auto_now_add=True, verbose_name='Applied on')),
                ('motivation', models.TextField(verbose_name='Motivation')),
                ('accepted', models.BooleanField(verbose_name='Accepted')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='position.Position', verbose_name='Position')),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
            },
        ),
    ]
