# Generated by Django 2.2.12 on 2020-09-06 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='accepted',
        ),
        migrations.AddField(
            model_name='application',
            name='application_status',
            field=models.CharField(choices=[('UNDER EXAMINATION', 'Under examination'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined')], default='UNDER EXAMINATION', max_length=100, verbose_name='Application status'),
        ),
    ]
