# Generated by Django 2.2.12 on 2020-09-09 01:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('position', '0002_auto_20200906_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='application_status',
            field=models.CharField(choices=[('UNDER_EXAMINATION', 'Under examination'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined')], default='UNDER_EXAMINATION', max_length=100, verbose_name='Application status'),
        ),
        migrations.AlterField(
            model_name='position',
            name='is_remote_job',
            field=models.BooleanField(verbose_name='Is remote'),
        ),
        migrations.AlterField(
            model_name='position',
            name='weekly_hours',
            field=models.FloatField(verbose_name='Weekly hours'),
        ),
    ]
