# Generated by Django 2.2.12 on 2020-07-24 01:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('address_line_1', models.CharField(max_length=100, verbose_name='Address line 1')),
                ('address_line_2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Address line 2')),
                ('postal_code', models.CharField(max_length=10, verbose_name='Postal code')),
                ('state_province', models.CharField(max_length=100, verbose_name='State/Province')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('latitude', models.FloatField(verbose_name='Latitude')),
                ('longitude', models.FloatField(verbose_name='Longitude')),
            ],
            options={
                'verbose_name': 'Cell',
                'verbose_name_plural': 'Cells',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Begin date')),
                ('end_time', models.DateTimeField(verbose_name='End date')),
                ('nb_volunteers_needed', models.PositiveIntegerField(default=0, verbose_name='Number of volunteers (needed)')),
                ('nb_volunteers_standby_needed', models.PositiveIntegerField(default=0, verbose_name='Number of volunteers on hold (needed)')),
                ('cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteer.Cell', verbose_name='Cell')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.CreateModel(
            name='TaskType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'TaskType',
                'verbose_name_plural': 'TaskTypes',
            },
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presence_duration_minutes', models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='Presence duration (in minutes)')),
                ('presence_status', models.CharField(choices=[('UNKNOWN', 'Unknown'), ('ABSENT', 'Absent'), ('PRESENT', 'Present')], default='UNKNOWN', max_length=100, verbose_name='Presence status')),
                ('is_standby', models.BooleanField(verbose_name='Is Stand-By')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='Registered at')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='volunteer.Event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Participation',
                'verbose_name_plural': 'Participations',
                'unique_together': {('event', 'user')},
            },
        ),
        migrations.AddField(
            model_name='event',
            name='task_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='volunteer.TaskType', verbose_name='Task type'),
        ),
        migrations.AddField(
            model_name='event',
            name='volunteers',
            field=models.ManyToManyField(blank=True, null=True, related_name='events', through='volunteer.Participation', to=settings.AUTH_USER_MODEL, verbose_name='Volunteers'),
        ),
    ]
