# Generated by Django 2.2.12 on 2020-07-27 21:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='volunteers',
            field=models.ManyToManyField(blank=True, related_name='events', through='volunteer.Participation', to=settings.AUTH_USER_MODEL, verbose_name='Volunteers'),
        ),
    ]
