# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-30 23:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='country',
            unique_together=set([]),
        ),
        migrations.AlterUniqueTogether(
            name='stateprovince',
            unique_together=set([]),
        ),
    ]
