# Generated by Django 2.2.12 on 2020-11-16 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='template_id',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Template ID'),
        ),
    ]
