# Generated by Django 2.2.12 on 2021-03-29 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BankConnetction',
            new_name='BankConnection',
        ),
    ]
