# Generated by Django 2.2.12 on 2021-03-29 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0002_auto_20210329_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankconnection',
            name='bank_connection',
            field=models.CharField(choices=[('STRIPE', 'Stripe'), ('PAYPAL', 'Paypal')], default='STRIPE', max_length=100, unique=True, verbose_name='Bank Connection'),
        ),
    ]
