# Generated by Django 2.2.12 on 2020-06-26 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_key', models.CharField(max_length=150, verbose_name='Notification Key')),
                ('email', models.CharField(max_length=1024, verbose_name='Email user')),
                ('notification_data', models.TextField(blank=True, null=True, verbose_name='Notification Data')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('is_read', models.BooleanField(default=False, verbose_name='Is Read')),
            ],
        ),
    ]
