# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-17 01:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
        ('volunteer', '0002_tasktype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.Address')),
            ],
            options={
                'verbose_name_plural': 'Cells',
            },
        ),
    ]
