# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-24 17:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('volunteer', '0003_cell'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='Begin date')),
                ('end_date', models.DateTimeField(verbose_name='End date')),
                ('nb_volunteers_needed', models.PositiveIntegerField(default=0, verbose_name='Number of volunteer needed')),
                ('nb_volunteers_standby_needed', models.PositiveIntegerField(default=0, verbose_name='Number of volunteers standby needed')),
                ('cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteer.Cell', verbose_name='Cell')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteer.Cycle', verbose_name='Cycle')),
                ('task_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteer.TaskType', verbose_name='Task type')),
                ('volunteers', models.ManyToManyField(blank=True, related_name='events', to=settings.AUTH_USER_MODEL, verbose_name='Volunteers')),
                ('volunteers_standby', models.ManyToManyField(blank=True, related_name='events_standby', to=settings.AUTH_USER_MODEL, verbose_name='Volunteers standby')),
            ],
            options={
                'verbose_name_plural': 'Events',
            },
        ),
    ]
