# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-30 23:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('volunteer', '0004_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standby', models.BooleanField(verbose_name='Standby')),
                ('subscription_date', models.DateTimeField(verbose_name='Subscription date')),
            ],
            options={
                'verbose_name_plural': 'Participations',
            },
        ),
        migrations.RemoveField(
            model_name='event',
            name='volunteers',
        ),
        migrations.RemoveField(
            model_name='event',
            name='volunteers_standby',
        ),
        migrations.AlterField(
            model_name='event',
            name='nb_volunteers_needed',
            field=models.PositiveIntegerField(default=0, verbose_name='Number of volunteers (needed)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='nb_volunteers_standby_needed',
            field=models.PositiveIntegerField(default=0, verbose_name='Number of volunteers on hold (needed)'),
        ),
        migrations.AddField(
            model_name='participation',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participation', to='volunteer.Event'),
        ),
        migrations.AddField(
            model_name='participation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='volunteers_new',
            field=models.ManyToManyField(blank=True, related_name='events', through='volunteer.Participation', to=settings.AUTH_USER_MODEL, verbose_name='Volunteers'),
        ),
        migrations.AlterUniqueTogether(
            name='participation',
            unique_together=set([('event', 'user')]),
        ),
        migrations.RenameField(
            model_name='event',
            old_name='volunteers_new',
            new_name='volunteers',
        ),
        migrations.AlterField(
            model_name='participation',
            name='subscription_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Subscription date'),
        ),
    ]
