# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-11 23:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0005_participation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('start_date',), 'verbose_name_plural': 'Events'},
        ),
    ]
