# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-30 23:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0005_auto_20171230_2350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='volunteers_new',
            new_name='volunteers',
        ),
    ]
