# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-16 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0006_event_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='presence_duration_minutes',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='participation',
            name='presence_status',
            field=models.CharField(choices=[('I', 'Initialisation'), ('A', 'Absent'), ('P', 'Present')], default='I', max_length=1),
        ),
    ]
