# Generated by Django 2.1.5 on 2019-06-03 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0009_auto_20190520_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='cell',
            name='email',
            field=models.EmailField(default='a@b.com', max_length=254, verbose_name='Email'),
            preserve_default=False,
        ),
    ]
