# Generated by Django 2.1.5 on 2019-06-03 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0009_auto_20190520_1040'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cycle',
            options={'ordering': ('-start_date',), 'verbose_name_plural': 'Cycles'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('-start_date',), 'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelOptions(
            name='participation',
            options={'ordering': ('-event__start_date',), 'verbose_name_plural': 'Participations'},
        ),
        migrations.AddField(
            model_name='cell',
            name='email',
            field=models.EmailField(default='a@b.com', max_length=254, verbose_name='Email'),
            preserve_default=False,
        ),
    ]
