# Generated by Django 2.1.5 on 2019-08-20 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('volunteer', '0008_cell_managers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=100, unique=True, verbose_name='Code')),
                ('coupon_wc_id', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('coupon_wc_log', models.TextField(blank=True, default='', null=True)),
                ('status', models.CharField(blank=True, choices=[('1', 'wc_create'), ('2', 'wc_delete')], default='1', max_length=100, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rechargeable_coupon', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Coupon Rechargeable',
            },
        ),
        migrations.CreateModel(
            name='CouponOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('email_sended', models.BooleanField(default=False)),
                ('added_to_wc', models.BooleanField(default=False)),
                ('wc_amount_total', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('wc_added_date', models.DateTimeField(blank=True, null=True)),
                ('coupon_wc_log', models.TextField(blank=True, default='', null=True)),
                ('status', models.CharField(blank=True, choices=[('1', 'add_to_wc_send_email'), ('2', 'send_email'), ('3', 'add_to_wc_only')], default='3', max_length=100, null=True)),
                ('coupon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='coupons.Coupon')),
                ('cycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='volunteer.Cycle', verbose_name='Cycle')),
            ],
            options={
                'verbose_name': 'Opération',
                'ordering': ('-pk',),
            },
        ),
    ]
