# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-25 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='coupon_wc_id',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='coupon_wc_log',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='email_sended',
            field=models.BooleanField(default=False),
        ),
    ]
