# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-09 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0002_auto_20180425_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='presence_duration_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
