# Generated by Django 2.1.3 on 2018-11-15 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0003_auto_20180709_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='cycle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='volunteer.Cycle', verbose_name='Cycle'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupon', to=settings.AUTH_USER_MODEL),
        ),
    ]
