# Generated by Django 2.1.5 on 2019-04-15 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('volunteer', '0008_cell_managers'),
        ('coupons', '0004_auto_20181115_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouponOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presence_duration_minutes', models.PositiveIntegerField(default=0)),
                ('email_sended', models.BooleanField(default=False)),
                ('added_to_wc', models.BooleanField(default=False)),
                ('wc_amount_total', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('wc_added_date', models.DateTimeField(blank=True, null=True)),
                ('coupon_wc_log', models.TextField(blank=True, default='', null=True)),
                ('status', models.CharField(blank=True, choices=[('1', 'add_to_wc'), ('2', 'send_email')], default='1', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RechargeableCoupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=100, unique=True, verbose_name='Code')),
                ('coupon_wc_id', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('coupon_wc_log', models.TextField(blank=True, default='', null=True)),
                ('status', models.CharField(blank=True, choices=[('1', 'wc_create'), ('2', 'wc_delete')], default='1', max_length=100, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rechargeable_coupon', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='couponoperation',
            name='coupon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='coupons.RechargeableCoupon'),
        ),
        migrations.AddField(
            model_name='couponoperation',
            name='cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='volunteer.Cycle', verbose_name='Cycle'),
        ),
    ]
