# Generated by Django 2.1.5 on 2019-04-18 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0005_auto_20190415_1553'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coupon',
            options={'verbose_name': '__Ancien Coupon'},
        ),
        migrations.AlterModelOptions(
            name='couponoperation',
            options={'ordering': ('-pk',), 'verbose_name': 'Opération'},
        ),
        migrations.AlterModelOptions(
            name='rechargeablecoupon',
            options={'verbose_name': 'Coupon Rechargeable'},
        ),
        migrations.RemoveField(
            model_name='couponoperation',
            name='presence_duration_minutes',
        ),
        migrations.AddField(
            model_name='couponoperation',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='couponoperation',
            name='status',
            field=models.CharField(blank=True, choices=[('1', 'add_to_wc_send_email'), ('2', 'send_email'), ('3', 'add_to_wc_only')], default='3', max_length=100, null=True),
        ),
    ]
