# Generated by Django 2.1.5 on 2019-05-23 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0006_auto_20190418_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rechargeablecoupon',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rechargeable_coupon', to=settings.AUTH_USER_MODEL),
        ),
    ]
