# Generated by Django 2.1.5 on 2019-05-27 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0007_auto_20190523_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponoperation',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rechargeablecoupon',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rechargeable_coupon', to=settings.AUTH_USER_MODEL),
        ),
    ]
